_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.5
            "8":
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
architecture:
    value: AE
example_1_original_dim:
    value: 49
initial_learning_rate:
    value: 0.0002
latent_dim:
    value: 20
num_training_updates:
    value: 1000
